In [1]:

# STEP 1: Load and inspect the combined LASI dataset

import pandas as pd
import numpy as np
from google.colab import files
from pathlib import Path

# 1. Upload the LASI combined Excel file
uploaded = files.upload()

excel_files = [
    name for name in uploaded
    if name.lower().endswith((".xlsx", ".xls"))
]

if not excel_files:
    raise ValueError("Please upload the combined LASI Excel workbook.")

# Select the LASI workbook if multiple files were uploaded
lasi_file = next(
    (name for name in excel_files if "lasi" in name.lower()),
    excel_files[0]
)

# 2. Load the main worksheet
xls = pd.ExcelFile(lasi_file)
print("Workbook:", lasi_file)
print("Available sheets:", xls.sheet_names)

df_lasi_original = pd.read_excel(lasi_file, sheet_name=0)

# Preserve a separate working copy
df_lasi = df_lasi_original.copy()

# Remove gender from the working copy if present
gender_cols = [
    c for c in df_lasi.columns
    if c.strip().lower() in {"gender", "sex"}
]
df_lasi = df_lasi.drop(columns=gender_cols)

print("\nOriginal shape:", df_lasi_original.shape)
print("Working shape:", df_lasi.shape)
print("Gender/sex columns removed:", gender_cols or "None found")

# 3. Inspect structure
print("\n--- COLUMN NAMES ---")
print(df_lasi.columns.tolist())

print("\n--- DATA TYPES ---")
print(df_lasi.dtypes.to_string())

print("\n--- FIRST FIVE ROWS ---")
display(df_lasi.head())

print("\n--- MISSING VALUES ---")
missing = pd.DataFrame({
    "missing_count": df_lasi.isna().sum(),
    "missing_percent": (
        df_lasi.isna().mean() * 100
    ).round(2)
})
display(missing.sort_values("missing_percent", ascending=False))

# 4. Duplicate checks
print("\n--- DUPLICATE CHECKS ---")
print("Exact duplicate rows:", df_lasi.duplicated().sum())

for col in ["person_id", "household_id"]:
    if col in df_lasi.columns:
        print(
            f"Rows with repeated {col}:",
            df_lasi[col].duplicated(keep=False).sum()
        )
        print(
            f"Unique {col} values:",
            df_lasi[col].nunique(dropna=True)
        )

# 5. Inspect unique values and possible survey codes
print("\n--- UNIQUE VALUES / CATEGORY CHECK ---")
for col in df_lasi.columns:
    s = df_lasi[col]
    print(f"\n{col}:")
    print("Unique non-null values:", s.nunique(dropna=True))
    if s.nunique(dropna=True) <= 20:
        print(s.value_counts(dropna=False).to_dict())
    else:
        print("Examples:", s.dropna().unique()[:10].tolist())

# 6. Numeric ranges to flag implausible values
print("\n--- NUMERIC SUMMARY ---")
display(df_lasi.describe(include="all").T)

# 7. Check key fields without assuming their definitions
key_fields = [
    "current_age",
    "last_menstrual_period_year",
    "hysterectomy_excessive_bleeding",
    "spatial_orientation_score",
    "heart_disease",
    "avg_systolic_bp",
    "avg_diastolic_bp",
    "bmi",
    "state"
]

print("\n--- KEY FIELD INSPECTION ---")
for col in key_fields:
    if col in df_lasi.columns:
        print(f"\n{col}")
        print("Non-null:", df_lasi[col].notna().sum())
        print("Distinct values:", df_lasi[col].nunique(dropna=True))
        print("Examples:", df_lasi[col].dropna().unique()[:15].tolist())

print("\nStep 1 inspection complete.")

Saving LASI Cleaned 2(1).xlsx to LASI Cleaned 2(1).xlsx
Saving NFHS Codes.xlsx to NFHS Codes.xlsx
Workbook: LASI Cleaned 2(1).xlsx
Available sheets: ['LASI Cleaned 2', 'Sheet1']

Original shape: (44901, 24)
Working shape: (44901, 24)
Gender/sex columns removed: None found

--- COLUMN NAMES ---
['person_id', 'household_id', 'current_age', 'age_first_marriage', 'last_menstrual_period_year', 'hysterectomy_excessive_bleeding', 'hot_flashes', 'insomnia', 'severe_fatigue', 'depression_2plus_weeks', 'ever_alcohol', 'vigorous_activity_frequency', 'moderate_activity_frequency', 'heart_disease', 'spatial_orientation_score', 'avg_systolic_bp', 'avg_diastolic_bp', 'avg_pulse', 'height_cm', 'weight_kg', 'waist_circumference_cm', 'hip_circumference_cm', 'state', 'bmi']

--- DATA TYPES ---
person_id                            int64
household_id                         int64
current_age                          int64
age_first_marriage                 float64
last_menstrual_period_year         float64
hysterectomy_excessive_bleeding    float64
hot_flashes                        float64
insomnia                           float64
severe_fatigue                     float64
depression_2plus_weeks             float64
ever_alcohol                       float64
vigorous_activity_frequency        float64
moderate_activity_frequency        float64
heart_disease                      float64
spatial_orientation_score          float64
avg_systolic_bp                    float64
avg_diastolic_bp                   float64
avg_pulse                          float64
height_cm                          float64
weight_kg                          float64
waist_circumference_cm             float64
hip_circumference_cm               float64
state                               object
bmi                                float64

--- FIRST FIVE ROWS ---

,person_id,household_id,current_age,age_first_marriage,last_menstrual_period_year,hysterectomy_excessive_bleeding,hot_flashes,insomnia,severe_fatigue,depression_2plus_weeks,...,spatial_orientation_score,avg_systolic_bp,avg_diastolic_bp,avg_pulse,height_cm,weight_kg,waist_circumference_cm,hip_circumference_cm,state,bmi
0,107033700050101,107033700050100,60,17.0,1998.0,NaN,NaN,1.0,0.0,0.0,...,1.0,134.0,84.0,81.0,150.4,65.0,101.8,105.7,Delhi,28.735429
1,107033700130102,107033700130100,50,15.0,2011.0,NaN,0.0,4.0,0.0,0.0,...,1.0,115.5,74.5,102.0,147.9,59.1,108.9,104.4,Delhi,27.017872
2,107033700180102,107033700180100,57,20.0,2003.0,NaN,0.0,2.0,0.0,0.0,...,1.0,116.5,87.5,82.0,154.8,68.0,99.6,110.3,Delhi,28.377034
3,107033700260102,107033700260100,66,19.0,1995.0,NaN,NaN,2.0,1.0,0.0,...,1.0,117.0,78.0,78.0,159.7,55.3,89.5,94.6,Delhi,21.682797
4,107033700330102,107033700330100,50,17.0,2013.0,NaN,0.0,2.0,0.0,0.0,...,1.0,115.5,85.0,94.0,154.1,71.4,105.4,102.9,Delhi,30.067196

--- MISSING VALUES ---

                                 missing_count  missing_percent
hysterectomy_excessive_bleeding          40215            89.56
hot_flashes                              17747            39.52
hip_circumference_cm                      4295             9.57
waist_circumference_cm                    4299             9.57
bmi                                       4279             9.53
weight_kg                                 4275             9.52
height_cm                                 4273             9.52
avg_systolic_bp                           3948             8.79
avg_pulse                                 3948             8.79
avg_diastolic_bp                          3948             8.79
last_menstrual_period_year                3637             8.10
age_first_marriage                         753             1.68
depression_2plus_weeks                     726             1.62
spatial_orientation_score                  624             1.39
vigorous_activity_frequency                329             0.73
moderate_activity_frequency                323             0.72
ever_alcohol                               314             0.70
severe_fatigue                             270             0.60
insomnia                                   124             0.28
heart_disease                               90             0.20
household_id                                 0             0.00
person_id                                    0             0.00
current_age                                  0             0.00
state                                        0             0.00

--- DUPLICATE CHECKS ---
Exact duplicate rows: 310
Rows with repeated person_id: 5280
Unique person_id values: 42261
Rows with repeated household_id: 11613
Unique household_id values: 38741

--- UNIQUE VALUES / CATEGORY CHECK ---

person_id:
Unique non-null values: 42261
Examples: [107033700050101, 107033700130102, 107033700180102, 107033700260102, 107033700330102, 107033700350102, 107033700410302, 107033700430102, 107033700460202, 107033700770101]

household_id:
Unique non-null values: 38741
Examples: [107033700050100, 107033700130100, 107033700180100, 107033700260100, 107033700330100, 107033700350100, 107033700410300, 107033700430100, 107033700460200, 107033700770100]

current_age:
Unique non-null values: 90
Examples: [60, 50, 57, 66, 31, 46, 34, 48, 63, 61]

age_first_marriage:
Unique non-null values: 47
Examples: [17.0, 15.0, 20.0, 19.0, 16.0, 24.0, 14.0, 21.0, 7.0, 18.0]

last_menstrual_period_year:
Unique non-null values: 82
Examples: [1998.0, 2011.0, 2003.0, 1995.0, 2013.0, 2017.0, 1984.0, 2002.0, 2008.0, 2004.0]

hysterectomy_excessive_bleeding:
Unique non-null values: 2
{nan: 40215, 0.0: 3259, 1.0: 1427}

hot_flashes:
Unique non-null values: 2
{0.0: 25706, nan: 17747, 1.0: 1448}

insomnia:
Unique non-null values: 4
{1.0: 25937, 2.0: 10563, 3.0: 5479, 4.0: 2798, nan: 124}

severe_fatigue:
Unique non-null values: 2
{0.0: 35267, 1.0: 9364, nan: 270}

depression_2plus_weeks:
Unique non-null values: 2
{0.0: 36714, 1.0: 7461, nan: 726}

ever_alcohol:
Unique non-null values: 2
{0.0: 42932, 1.0: 1655, nan: 314}

vigorous_activity_frequency:
Unique non-null values: 5
{5.0: 30577, 1.0: 8021, 2.0: 2521, 4.0: 2038, 3.0: 1415, nan: 329}

moderate_activity_frequency:
Unique non-null values: 5
{1.0: 29207, 5.0: 10676, 2.0: 2524, 3.0: 1305, 4.0: 866, nan: 323}

heart_disease:
Unique non-null values: 2
{0.0: 43519, 1.0: 1292, nan: 90}

spatial_orientation_score:
Unique non-null values: 2
{1.0: 43696, nan: 624, 0.0: 581}

avg_systolic_bp:
Unique non-null values: 271
Examples: [134.0, 115.5, 116.5, 117.0, 102.5, 101.0, 109.5, 144.5, 168.5, 129.0]

avg_diastolic_bp:
Unique non-null values: 172
Examples: [84.0, 74.5, 87.5, 78.0, 85.0, 76.0, 80.0, 70.0, 78.5, 73.0]

avg_pulse:
Unique non-null values: 188
Examples: [81.0, 102.0, 82.0, 78.0, 94.0, 87.0, 76.0, 68.0, 83.0, 79.5]

height_cm:
Unique non-null values: 508
Examples: [150.4, 147.9, 154.8, 159.7, 154.1, 155.2, 154.3, 139.5, 156.2, 145.5]

weight_kg:
Unique non-null values: 962
Examples: [65.0, 59.1, 68.0, 55.3, 71.4, 44.5, 60.0, 46.5, 53.2, 50.2]

waist_circumference_cm:
Unique non-null values: 851
Examples: [101.8, 108.9, 99.6, 89.5, 105.4, 72.4, 87.6, 80.2, 78.2, 83.9]

hip_circumference_cm:
Unique non-null values: 808
Examples: [105.7, 104.4, 110.3, 94.6, 102.9, 85.7, 104.7, 90.6, 90.5, 95.3]

state:
Unique non-null values: 36
Examples: ['Delhi', 'West Bengal', 'Maharashtra', 'Tamil Nadu', 'Jammu and Kashmir', 'Himachal Pradesh', 'Punjab', 'Chandigarh', 'Uttarakhand', 'Haryana']

bmi:
Unique non-null values: 33164
Examples: [28.73542892711634, 27.017871567735998, 28.37703396564042, 21.68279675926489, 30.06719639395776, 18.474665214156666, 25.201094231511526, 23.894862604540023, 21.804672757766486, 23.71252110863121]

--- NUMERIC SUMMARY ---

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
person_id,44901.0,NaN,NaN,NaN,119649480584781.1875,10167750265656.875,101000100040102.0,110066603270202.0,120126300260102.0,128185701880201.0,136242502730102.0
household_id,44901.0,NaN,NaN,NaN,119649480584787.328125,10167750265663.291016,101000100040100.0,110066603270200.0,120126300260100.0,128185701880200.0,136242502730100.0
current_age,44901.0,NaN,NaN,NaN,56.304292,12.126682,18.0,47.0,55.0,65.0,110.0
age_first_marriage,44148.0,NaN,NaN,NaN,17.753443,4.689714,5.0,15.0,17.0,20.0,55.0
last_menstrual_period_year,41264.0,NaN,NaN,NaN,2006.413702,12.044315,1931.0,2000.0,2010.0,2017.0,2021.0
hysterectomy_excessive_bleeding,4686.0,NaN,NaN,NaN,0.304524,0.460255,0.0,0.0,0.0,1.0,1.0
hot_flashes,27154.0,NaN,NaN,NaN,0.053325,0.224686,0.0,0.0,0.0,0.0,1.0
insomnia,44777.0,NaN,NaN,NaN,1.668089,0.917286,1.0,1.0,1.0,2.0,4.0
severe_fatigue,44631.0,NaN,NaN,NaN,0.209809,0.407177,0.0,0.0,0.0,0.0,1.0
depression_2plus_weeks,44175.0,NaN,NaN,NaN,0.168896,0.374665,0.0,0.0,0.0,0.0,1.0
ever_alcohol,44587.0,NaN,NaN,NaN,0.037118,0.189054,0.0,0.0,0.0,0.0,1.0
vigorous_activity_frequency,44572.0,NaN,NaN,NaN,4.001279,1.601144,1.0,3.0,5.0,5.0,5.0
moderate_activity_frequency,44578.0,NaN,NaN,NaN,2.13141,1.70305,1.0,1.0,1.0,4.0,5.0
heart_disease,44811.0,NaN,NaN,NaN,0.028832,0.167337,0.0,0.0,0.0,0.0,1.0
spatial_orientation_score,44277.0,NaN,NaN,NaN,0.986878,0.113798,0.0,1.0,1.0,1.0,1.0
avg_systolic_bp,40953.0,NaN,NaN,NaN,127.529864,19.49832,60.0,113.0,125.0,139.5,233.5
avg_diastolic_bp,40953.0,NaN,NaN,NaN,81.053781,10.235571,41.0,74.0,80.5,87.5,163.0
avg_pulse,40953.0,NaN,NaN,NaN,81.911166,11.352921,32.0,74.0,81.5,89.0,147.0
height_cm,40628.0,NaN,NaN,NaN,150.348359,6.416291,99.5,146.3,150.3,154.5,190.6
weight_kg,40626.0,NaN,NaN,NaN,53.596681,12.95284,20.05,43.9,52.3,61.7,138.9
waist_circumference_cm,40602.0,NaN,NaN,NaN,85.711327,13.478166,40.1,76.2,85.6,95.0,160.7
hip_circumference_cm,40606.0,NaN,NaN,NaN,93.327661,11.54364,41.7,85.2,92.5,100.4,169.2
state,44901,36,West Bengal,3049,NaN,NaN,NaN,NaN,NaN,NaN,NaN
bmi,40622.0,NaN,NaN,NaN,23.613731,5.116065,9.335107,19.813748,23.134987,26.796041,55.55088

--- KEY FIELD INSPECTION ---

current_age
Non-null: 44901
Distinct values: 90
Examples: [60, 50, 57, 66, 31, 46, 34, 48, 63, 61, 45, 33, 65, 49, 62]

last_menstrual_period_year
Non-null: 41264
Distinct values: 82
Examples: [1998.0, 2011.0, 2003.0, 1995.0, 2013.0, 2017.0, 1984.0, 2002.0, 2008.0, 2004.0, 2016.0, 1983.0, 2015.0, 1990.0, 1978.0]

hysterectomy_excessive_bleeding
Non-null: 4686
Distinct values: 2
Examples: [0.0, 1.0]

spatial_orientation_score
Non-null: 44277
Distinct values: 2
Examples: [1.0, 0.0]

heart_disease
Non-null: 44811
Distinct values: 2
Examples: [0.0, 1.0]

avg_systolic_bp
Non-null: 40953
Distinct values: 271
Examples: [134.0, 115.5, 116.5, 117.0, 102.5, 101.0, 109.5, 144.5, 168.5, 129.0, 103.5, 110.0, 98.5, 149.5, 123.0]

avg_diastolic_bp
Non-null: 40953
Distinct values: 172
Examples: [84.0, 74.5, 87.5, 78.0, 85.0, 76.0, 80.0, 70.0, 78.5, 73.0, 87.0, 102.0, 77.5, 66.5, 72.5]

bmi
Non-null: 40622
Distinct values: 33164
Examples: [28.73542892711634, 27.017871567735998, 28.37703396564042, 21.68279675926489, 30.06719639395776, 18.474665214156666, 25.201094231511526, 23.894862604540023, 21.804672757766486, 23.71252110863121, 30.607466613286054, 28.66516750629335, 22.525689915686055, 19.142216500679037, 15.073629025177107]

state
Non-null: 44901
Distinct values: 36
Examples: ['Delhi', 'West Bengal', 'Maharashtra', 'Tamil Nadu', 'Jammu and Kashmir', 'Himachal Pradesh', 'Punjab', 'Chandigarh', 'Uttarakhand', 'Haryana', 'Rajasthan', 'Uttar Pradesh', 'Bihar', 'Sikkim', 'Arunachal Pradesh']

Step 1 inspection complete.

In [2]:

# STEP 2: Audit repeated respondents and menopause-target feasibility

import pandas as pd
import numpy as np

# Check that Step 1 has been run
assert "df_lasi" in globals(), "Run Step 1 first."

df_audit = df_lasi.copy()

# A. Investigate repeated person IDs before removing anything
print("A. PERSON ID AUDIT")
print("Rows:", len(df_audit))
print("Unique people:", df_audit["person_id"].nunique())
print("Repeated-ID rows:",
      df_audit["person_id"].duplicated(keep=False).sum())

id_counts = df_audit["person_id"].value_counts()
repeated_ids = id_counts[id_counts > 1].index

duplicate_id_rows = df_audit[
    df_audit["person_id"].isin(repeated_ids)
].sort_values("person_id")

print("\nRows for the first 10 repeated IDs:")
display(duplicate_id_rows.head(10))

# How many repeated IDs have conflicting values?
compare_cols = [
    c for c in df_audit.columns
    if c not in ["person_id", "household_id"]
]

conflict_counts = (
    duplicate_id_rows.groupby("person_id")[compare_cols]
    .nunique(dropna=True)
)

conflicting_ids = (conflict_counts > 1).any(axis=1)

print("\nRepeated IDs with conflicting non-ID data:",
      int(conflicting_ids.sum()))
print("Repeated IDs with identical observed non-ID data:",
      int((~conflicting_ids).sum()))

# B. Check exact duplicate rows
print("\nB. EXACT DUPLICATES")
print("Exact duplicate rows:", df_audit.duplicated().sum())

# C. Audit the last menstrual period year
print("\nC. MENSTRUAL YEAR AUDIT")
lmp = pd.to_numeric(
    df_audit["last_menstrual_period_year"], errors="coerce"
)
age = pd.to_numeric(df_audit["current_age"], errors="coerce")

# LASI Wave 1 was conducted mainly in 2017–2018.
# Use this only as a plausibility screen, not as the target yet.
print("Year counts:")
display(lmp.value_counts(dropna=False).sort_index())

print("\nRows with year after 2018:", int((lmp > 2018).sum()))
print("Rows with year before 1930:", int((lmp < 1930).sum()))
print("Rows with LMP year later than respondent birth-year estimate:",
      int(((lmp > (2018 - age)) & lmp.notna() & age.notna()).sum()))

# Calculate a rough interval for investigation only.
# This is NOT a validated menopause-age target.
rough_years_since_lmp = 2018 - lmp
rough_age_at_lmp = age - rough_years_since_lmp

print("\nApproximate age at last period (diagnostic only):")
display(rough_age_at_lmp.describe())

print("\nApproximate ages outside 25–65:",
      int((~rough_age_at_lmp.between(25, 65)).sum()))

# D. Inspect hysterectomy field and its relationship with LMP availability
print("\nD. HYSTERECTOMY FIELD")
display(
    df_audit["hysterectomy_excessive_bleeding"]
    .value_counts(dropna=False)
    .rename_axis("value")
    .to_frame("count")
)

print("\nLMP availability by hysterectomy field value:")
display(pd.crosstab(
    df_audit["hysterectomy_excessive_bleeding"],
    df_audit["last_menstrual_period_year"].isna(),
    margins=True
))

# E. Cognitive score and cardiovascular indicator distributions
print("\nE. HEALTH INDICATORS")
for col in [
    "spatial_orientation_score",
    "heart_disease",
    "avg_systolic_bp",
    "avg_diastolic_bp"
]:
    print(f"\n{col}")
    print(df_audit[col].describe())
    print(df_audit[col].value_counts(dropna=False).head(15))

print("\nAudit complete. No rows have been deleted.")

A. PERSON ID AUDIT
Rows: 44901
Unique people: 42261
Repeated-ID rows: 5280

Rows for the first 10 repeated IDs:

,person_id,household_id,current_age,age_first_marriage,last_menstrual_period_year,hysterectomy_excessive_bleeding,hot_flashes,insomnia,severe_fatigue,depression_2plus_weeks,...,spatial_orientation_score,avg_systolic_bp,avg_diastolic_bp,avg_pulse,height_cm,weight_kg,waist_circumference_cm,hip_circumference_cm,state,bmi
8063,107033700050101,107033700050100,60,17.0,1998.0,NaN,NaN,1.0,0.0,0.0,...,1.0,134.0,84.0,81.0,150.4,65.0,101.8,105.7,Delhi,28.735429
0,107033700050101,107033700050100,60,17.0,1998.0,NaN,NaN,1.0,0.0,0.0,...,1.0,134.0,84.0,81.0,150.4,65.0,101.8,105.7,Delhi,28.735429
1,107033700130102,107033700130100,50,15.0,2011.0,NaN,0.0,4.0,0.0,0.0,...,1.0,115.5,74.5,102.0,147.9,59.1,108.9,104.4,Delhi,27.017872
8064,107033700130102,107033700130100,50,15.0,2011.0,NaN,0.0,4.0,0.0,0.0,...,1.0,115.5,74.5,102.0,147.9,59.1,108.9,104.4,Delhi,27.017872
8065,107033700180102,107033700180100,57,20.0,2003.0,NaN,0.0,2.0,0.0,0.0,...,1.0,116.5,87.5,82.0,154.8,68.0,99.6,110.3,Delhi,28.377034
2,107033700180102,107033700180100,57,20.0,2003.0,NaN,0.0,2.0,0.0,0.0,...,1.0,116.5,87.5,82.0,154.8,68.0,99.6,110.3,Delhi,28.377034
3,107033700260102,107033700260100,66,19.0,1995.0,NaN,NaN,2.0,1.0,0.0,...,1.0,117.0,78.0,78.0,159.7,55.3,89.5,94.6,Delhi,21.682797
8066,107033700260102,107033700260100,66,19.0,1995.0,NaN,NaN,2.0,1.0,0.0,...,1.0,117.0,78.0,78.0,159.7,55.3,89.5,94.6,Delhi,21.682797
8067,107033700330102,107033700330100,50,17.0,2013.0,NaN,0.0,2.0,0.0,0.0,...,1.0,115.5,85.0,94.0,154.1,71.4,105.4,102.9,Delhi,30.067196
4,107033700330102,107033700330100,50,17.0,2013.0,NaN,0.0,2.0,0.0,0.0,...,1.0,115.5,85.0,94.0,154.1,71.4,105.4,102.9,Delhi,30.067196

Repeated IDs with conflicting non-ID data: 2328
Repeated IDs with identical observed non-ID data: 312

B. EXACT DUPLICATES
Exact duplicate rows: 310

C. MENSTRUAL YEAR AUDIT
Year counts:

last_menstrual_period_year
1931.0       1
1932.0       1
1937.0       2
1940.0       4
1944.0       2
          ...
2018.0    5423
2019.0     552
2020.0      33
2021.0     173
NaN       3637
Name: count, Length: 83, dtype: int64

Rows with year after 2018: 758
Rows with year before 1930: 0
Rows with LMP year later than respondent birth-year estimate: 41228

Approximate age at last period (diagnostic only):

count    41264.000000
mean        43.943219
std          7.818742
min         -2.000000
25%         41.000000
50%         45.000000
75%         48.000000
max         82.000000
dtype: float64

Approximate ages outside 25–65: 4865

D. HYSTERECTOMY FIELD

       count
value
NaN    40215
0.0     3259
1.0     1427

LMP availability by hysterectomy field value:

last_menstrual_period_year       False  True   All
hysterectomy_excessive_bleeding
0.0                               2999   260  3259
1.0                               1363    64  1427
All                               4362   324  4686

E. HEALTH INDICATORS

spatial_orientation_score
count    44277.000000
mean         0.986878
std          0.113798
min          0.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          1.000000
Name: spatial_orientation_score, dtype: float64
spatial_orientation_score
1.0    43696
NaN      624
0.0      581
Name: count, dtype: int64

heart_disease
count    44811.000000
mean         0.028832
std          0.167337
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: heart_disease, dtype: float64
heart_disease
0.0    43519
1.0     1292
NaN       90
Name: count, dtype: int64

avg_systolic_bp
count    40953.000000
mean       127.529864
std         19.498320
min         60.000000
25%        113.000000
50%        125.000000
75%        139.500000
max        233.500000
Name: avg_systolic_bp, dtype: float64
avg_systolic_bp
NaN      3948
122.0     479
120.0     473
119.5     462
125.0     461
117.0     458
123.5     458
118.0     455
114.0     452
129.0     452
122.5     445
116.0     440
117.5     436
123.0     432
118.5     429
Name: count, dtype: int64

avg_diastolic_bp
count    40953.000000
mean        81.053781
std         10.235571
min         41.000000
25%         74.000000
50%         80.500000
75%         87.500000
max        163.000000
Name: avg_diastolic_bp, dtype: float64
avg_diastolic_bp
NaN     3948
77.0     909
76.0     908
78.0     870
82.0     837
83.0     833
81.0     829
79.0     828
80.0     827
76.5     801
84.0     797
77.5     786
85.0     786
79.5     784
82.5     784
Name: count, dtype: int64

Audit complete. No rows have been deleted.

In [3]:

# STEP 3: Investigate repeated respondent IDs
import pandas as pd

assert "df_lasi" in globals(), "Run Step 1 first."

df_check = df_lasi.copy()

# 1. How many times does each respondent ID appear?
id_counts = df_check["person_id"].value_counts()

print("A. RESPONDENT ID FREQUENCY")
print("IDs appearing once:", int((id_counts == 1).sum()))
print("IDs appearing twice:", int((id_counts == 2).sum()))
print("IDs appearing 3+ times:", int((id_counts >= 3).sum()))
print("Maximum rows for one ID:", int(id_counts.max()))

# 2. Identify columns that conflict within repeated IDs
repeated = df_check[
    df_check["person_id"].isin(id_counts[id_counts > 1].index)
].copy()

compare_cols = [
    c for c in df_check.columns
    if c not in ["person_id", "household_id"]
]

conflicts = repeated.groupby("person_id")[compare_cols].nunique(
    dropna=True
)

conflicting_ids = conflicts.index[(conflicts > 1).any(axis=1)]
conflict_columns = (conflicts > 1).sum().sort_values(ascending=False)

print("\nB. COLUMNS MOST OFTEN CONFLICTING WITHIN THE SAME ID")
display(conflict_columns[conflict_columns > 0].to_frame(
    "number_of_ID_groups_with_conflicts"
).head(15))

print("\nC. EXAMPLES OF CONFLICTING RESPONDENT RECORDS")
example_ids = list(conflicting_ids[:3])

if example_ids:
    display(
        df_check[df_check["person_id"].isin(example_ids)]
        .sort_values("person_id")
    )
else:
    print("No conflicting repeated IDs found.")

# 3. Check whether exact duplicates account for the repeated rows
print("\nD. EXACT DUPLICATE CHECK")
print("Exact duplicate rows:", int(df_check.duplicated().sum()))
print("Rows remaining if exact duplicates alone were removed:",
      len(df_check.drop_duplicates()))

print("\nInvestigation complete. Original df_lasi remains unchanged.")

A. RESPONDENT ID FREQUENCY
IDs appearing once: 39621
IDs appearing twice: 2640
IDs appearing 3+ times: 0
Maximum rows for one ID: 2

B. COLUMNS MOST OFTEN CONFLICTING WITHIN THE SAME ID

                           number_of_ID_groups_with_conflicts
bmi                                                      2311
spatial_orientation_score                                  98

C. EXAMPLES OF CONFLICTING RESPONDENT RECORDS

,person_id,household_id,current_age,age_first_marriage,last_menstrual_period_year,hysterectomy_excessive_bleeding,hot_flashes,insomnia,severe_fatigue,depression_2plus_weeks,...,spatial_orientation_score,avg_systolic_bp,avg_diastolic_bp,avg_pulse,height_cm,weight_kg,waist_circumference_cm,hip_circumference_cm,state,bmi
0,107033700050101,107033700050100,60,17.0,1998.0,NaN,NaN,1.0,0.0,0.0,...,1.0,134.0,84.0,81.0,150.4,65.0,101.8,105.7,Delhi,28.735429
8063,107033700050101,107033700050100,60,17.0,1998.0,NaN,NaN,1.0,0.0,0.0,...,1.0,134.0,84.0,81.0,150.4,65.0,101.8,105.7,Delhi,28.735429
1,107033700130102,107033700130100,50,15.0,2011.0,NaN,0.0,4.0,0.0,0.0,...,1.0,115.5,74.5,102.0,147.9,59.1,108.9,104.4,Delhi,27.017872
8064,107033700130102,107033700130100,50,15.0,2011.0,NaN,0.0,4.0,0.0,0.0,...,1.0,115.5,74.5,102.0,147.9,59.1,108.9,104.4,Delhi,27.017872
2,107033700180102,107033700180100,57,20.0,2003.0,NaN,0.0,2.0,0.0,0.0,...,1.0,116.5,87.5,82.0,154.8,68.0,99.6,110.3,Delhi,28.377034
8065,107033700180102,107033700180100,57,20.0,2003.0,NaN,0.0,2.0,0.0,0.0,...,1.0,116.5,87.5,82.0,154.8,68.0,99.6,110.3,Delhi,28.377034

D. EXACT DUPLICATE CHECK
Exact duplicate rows: 310
Rows remaining if exact duplicates alone were removed: 44591

Investigation complete. Original df_lasi remains unchanged.

In [4]:

# STEP 4: Remove exact duplicate rows only
assert "df_lasi" in globals(), "Run Step 1 first."

df_lasi_work = df_lasi.copy()

before = len(df_lasi_work)
df_lasi_work = df_lasi_work.drop_duplicates().copy()
after = len(df_lasi_work)

print("Original rows:", before)
print("Exact duplicate rows removed:", before - after)
print("Rows in working copy:", after)
print("Unique person IDs:", df_lasi_work["person_id"].nunique())
print("Remaining rows belonging to repeated IDs:",
      int(df_lasi_work["person_id"].duplicated(keep=False).sum()))

print("\nOriginal df_lasi unchanged:", len(df_lasi) == before)

Original rows: 44901
Exact duplicate rows removed: 310
Rows in working copy: 44591
Unique person IDs: 42261
Remaining rows belonging to repeated IDs: 4660

Original df_lasi unchanged: True

In [5]:

# STEP 5: Profile remaining repeated-ID conflicts
assert "df_lasi_work" in globals(), "Run Step 4 first."

df = df_lasi_work.copy()

id_counts = df["person_id"].value_counts()
repeated_ids = id_counts[id_counts > 1].index

repeated = df[df["person_id"].isin(repeated_ids)].copy()

compare_cols = [
    c for c in df.columns
    if c not in ["person_id", "household_id"]
]

conflicts = repeated.groupby("person_id")[compare_cols].nunique(
    dropna=True
)

conflict_summary = (
    (conflicts > 1)
    .sum()
    .sort_values(ascending=False)
    .rename("IDs_with_conflicts")
    .to_frame()
)

print("Repeated IDs:", len(repeated_ids))
print("\nColumns with conflicting values:")
display(conflict_summary[conflict_summary["IDs_with_conflicts"] > 0])

print("\nExample: repeated IDs with conflicting BMI")
bmi_conflict_ids = conflicts.index[conflicts["bmi"] > 1][:5]

if len(bmi_conflict_ids):
    display(
        df[df["person_id"].isin(bmi_conflict_ids)]
        .sort_values("person_id")
    )
else:
    print("No BMI conflicts found.")

Repeated IDs: 2330

Columns with conflicting values:

                           IDs_with_conflicts
bmi                                      2311
spatial_orientation_score                  98

Example: repeated IDs with conflicting BMI

,person_id,household_id,current_age,age_first_marriage,last_menstrual_period_year,hysterectomy_excessive_bleeding,hot_flashes,insomnia,severe_fatigue,depression_2plus_weeks,...,spatial_orientation_score,avg_systolic_bp,avg_diastolic_bp,avg_pulse,height_cm,weight_kg,waist_circumference_cm,hip_circumference_cm,state,bmi
0,107033700050101,107033700050100,60,17.0,1998.0,NaN,NaN,1.0,0.0,0.0,...,1.0,134.0,84.0,81.0,150.4,65.0,101.8,105.7,Delhi,28.735429
8063,107033700050101,107033700050100,60,17.0,1998.0,NaN,NaN,1.0,0.0,0.0,...,1.0,134.0,84.0,81.0,150.4,65.0,101.8,105.7,Delhi,28.735429
8064,107033700130102,107033700130100,50,15.0,2011.0,NaN,0.0,4.0,0.0,0.0,...,1.0,115.5,74.5,102.0,147.9,59.1,108.9,104.4,Delhi,27.017872
1,107033700130102,107033700130100,50,15.0,2011.0,NaN,0.0,4.0,0.0,0.0,...,1.0,115.5,74.5,102.0,147.9,59.1,108.9,104.4,Delhi,27.017872
8065,107033700180102,107033700180100,57,20.0,2003.0,NaN,0.0,2.0,0.0,0.0,...,1.0,116.5,87.5,82.0,154.8,68.0,99.6,110.3,Delhi,28.377034
2,107033700180102,107033700180100,57,20.0,2003.0,NaN,0.0,2.0,0.0,0.0,...,1.0,116.5,87.5,82.0,154.8,68.0,99.6,110.3,Delhi,28.377034
3,107033700260102,107033700260100,66,19.0,1995.0,NaN,NaN,2.0,1.0,0.0,...,1.0,117.0,78.0,78.0,159.7,55.3,89.5,94.6,Delhi,21.682797
8066,107033700260102,107033700260100,66,19.0,1995.0,NaN,NaN,2.0,1.0,0.0,...,1.0,117.0,78.0,78.0,159.7,55.3,89.5,94.6,Delhi,21.682797
4,107033700330102,107033700330100,50,17.0,2013.0,NaN,0.0,2.0,0.0,0.0,...,1.0,115.5,85.0,94.0,154.1,71.4,105.4,102.9,Delhi,30.067196
8067,107033700330102,107033700330100,50,17.0,2013.0,NaN,0.0,2.0,0.0,0.0,...,1.0,115.5,85.0,94.0,154.1,71.4,105.4,102.9,Delhi,30.067196

In [6]:

# STEP 6: Display genuine BMI conflicts side by side
assert "df_lasi_work" in globals(), "Run Step 4 first."

df = df_lasi_work.copy()

bmi_numeric = pd.to_numeric(df["bmi"], errors="coerce")
df["_bmi_check"] = bmi_numeric

bmi_counts = df.groupby("person_id")["_bmi_check"].nunique(
    dropna=True
)
bmi_conflict_ids = bmi_counts[bmi_counts > 1].index[:5]

cols = [
    "person_id", "household_id", "current_age",
    "height_cm", "weight_kg", "bmi",
    "spatial_orientation_score", "state"
]

print("Number of IDs with conflicting BMI:", int((bmi_counts > 1).sum()))

if len(bmi_conflict_ids):
    display(
        df[df["person_id"].isin(bmi_conflict_ids)][cols]
        .sort_values("person_id")
    )
else:
    print("No conflicting BMI values found.")

df.drop(columns="_bmi_check", inplace=True)

Number of IDs with conflicting BMI: 2311

,person_id,household_id,current_age,height_cm,weight_kg,bmi,spatial_orientation_score,state
0,107033700050101,107033700050100,60,150.4,65.0,28.735429,1.0,Delhi
8063,107033700050101,107033700050100,60,150.4,65.0,28.735429,1.0,Delhi
8064,107033700130102,107033700130100,50,147.9,59.1,27.017872,1.0,Delhi
1,107033700130102,107033700130100,50,147.9,59.1,27.017872,1.0,Delhi
8065,107033700180102,107033700180100,57,154.8,68.0,28.377034,1.0,Delhi
2,107033700180102,107033700180100,57,154.8,68.0,28.377034,1.0,Delhi
3,107033700260102,107033700260100,66,159.7,55.3,21.682797,1.0,Delhi
8066,107033700260102,107033700260100,66,159.7,55.3,21.682797,1.0,Delhi
4,107033700330102,107033700330100,50,154.1,71.4,30.067196,1.0,Delhi
8067,107033700330102,107033700330100,50,154.1,71.4,30.067196,1.0,Delhi

In [7]:

# STEP 7: Assess a provisional menopause age-span target
import pandas as pd
import numpy as np

assert "df_lasi_work" in globals(), "Run Step 4 first."

df_model = df_lasi_work.copy()

age = pd.to_numeric(df_model["current_age"], errors="coerce")
lmp_year = pd.to_numeric(
    df_model["last_menstrual_period_year"], errors="coerce"
)

# Approximate age at last period, assuming survey reference year 2018
df_model["approx_age_at_last_period"] = age - (2018 - lmp_year)

# Keep the original values; create labels only for assessment
valid = df_model["approx_age_at_last_period"].between(25, 65)

bins = [25, 30, 35, 40, 45, 50, 55, 60, 66]
labels = ["25–29", "30–34", "35–39", "40–44",
          "45–49", "50–54", "55–59", "60–65"]

df_model["provisional_age_span"] = pd.cut(
    df_model["approx_age_at_last_period"],
    bins=bins,
    labels=labels,
    right=False
)

print("Total rows:", len(df_model))
print("Rows with approximate ages in 25–65:", int(valid.sum()))
print("Rows outside that range or missing:",
      int((~valid).sum()))

print("\nProvisional age-span counts:")
display(
    df_model.loc[valid, "provisional_age_span"]
    .value_counts(sort=False)
    .rename_axis("age_span")
    .to_frame("respondent_count")
)

print("\nThese are provisional bands based on reported last-period year.")
print("They are not yet verified natural-menopause labels.")

Total rows: 44591
Rows with approximate ages in 25–65: 39762
Rows outside that range or missing: 4829

Provisional age-span counts:

          respondent_count
age_span
25–29                  597
30–34                 1588
35–39                 4667
40–44                10851
45–49                14966
50–54                 5427
55–59                 1281
60–65                  385

These are provisional bands based on reported last-period year.
They are not yet verified natural-menopause labels.

In [8]:

# STEP 8: Create the first modelling dataset
import pandas as pd
import numpy as np

assert "df_model" in globals(), "Run Step 7 first."

# Keep only rows with a provisional target in the 25–65 range
df_train = df_model[
    df_model["provisional_age_span"].notna()
].copy()

# Features currently available in the LASI dataset
candidate_features = [
    "current_age",
    "age_first_marriage",
    "hot_flashes",
    "insomnia",
    "severe_fatigue",
    "depression_2plus_weeks",
    "ever_alcohol",
    "vigorous_activity_frequency",
    "moderate_activity_frequency",
    "heart_disease",
    "avg_systolic_bp",
    "avg_diastolic_bp",
    "avg_pulse",
    "height_cm",
    "weight_kg",
    "waist_circumference_cm",
    "hip_circumference_cm",
    "bmi",
    "state"
]

features = [c for c in candidate_features if c in df_train.columns]

print("Rows available for modelling:", len(df_train))
print("Target: provisional_age_span")
print("\nTarget counts:")
display(df_train["provisional_age_span"].value_counts(sort=False))

print("\nFeature missingness (%):")
display(
    (df_train[features].isna().mean() * 100)
    .sort_values(ascending=False)
    .round(2)
    .to_frame("missing_percent")
)

print("\nFeature columns available:", len(features))
print("Modelling dataset created. No model has been trained yet.")

Rows available for modelling: 39762
Target: provisional_age_span

Target counts:

provisional_age_span
25–29      597
30–34     1588
35–39     4667
40–44    10851
45–49    14966
50–54     5427
55–59     1281
60–65      385
Name: count, dtype: int64

Feature missingness (%):

                             missing_percent
hot_flashes                            36.02
waist_circumference_cm                  7.76
hip_circumference_cm                    7.75
bmi                                     7.72
weight_kg                               7.71
height_cm                               7.71
avg_systolic_bp                         7.05
avg_pulse                               7.05
avg_diastolic_bp                        7.05
age_first_marriage                      1.57
depression_2plus_weeks                  0.42
vigorous_activity_frequency             0.40
moderate_activity_frequency             0.39
ever_alcohol                            0.37
severe_fatigue                          0.33
heart_disease                           0.01
current_age                             0.00
insomnia                                0.00
state                                   0.00

Feature columns available: 19
Modelling dataset created. No model has been trained yet.

In [9]:

# STEP 9: Define leakage-safe features and target
from sklearn.model_selection import train_test_split

assert "df_train" in globals(), "Run Step 8 first."

# Exclude current_age because it was used to construct the target.
# Exclude last_menstrual_period_year because it directly defines the target.
# Exclude BMI because it is derived from height and weight.
exclude_cols = {
    "person_id",
    "household_id",
    "current_age",
    "last_menstrual_period_year",
    "approx_age_at_last_period",
    "provisional_age_span",
    "bmi"
}

feature_cols = [
    c for c in df_train.columns
    if c not in exclude_cols
    and c not in ["spatial_orientation_score"]
]

# Use only the available candidate predictors from Step 8
candidate_features = [
    "age_first_marriage",
    "hot_flashes",
    "insomnia",
    "severe_fatigue",
    "depression_2plus_weeks",
    "ever_alcohol",
    "vigorous_activity_frequency",
    "moderate_activity_frequency",
    "heart_disease",
    "avg_systolic_bp",
    "avg_diastolic_bp",
    "avg_pulse",
    "height_cm",
    "weight_kg",
    "waist_circumference_cm",
    "hip_circumference_cm",
    "state"
]

feature_cols = [c for c in candidate_features if c in df_train.columns]

X = df_train[feature_cols].copy()
y = df_train["provisional_age_span"].astype(str)

print("X shape:", X.shape)
print("Target shape:", y.shape)
print("Features:", feature_cols)
print("\nTarget classes:")
print(y.value_counts())

print("\nTarget leakage columns excluded:",
      ["current_age", "last_menstrual_period_year",
       "approx_age_at_last_period", "provisional_age_span"])

X shape: (39762, 17)
Target shape: (39762,)
Features: ['age_first_marriage', 'hot_flashes', 'insomnia', 'severe_fatigue', 'depression_2plus_weeks', 'ever_alcohol', 'vigorous_activity_frequency', 'moderate_activity_frequency', 'heart_disease', 'avg_systolic_bp', 'avg_diastolic_bp', 'avg_pulse', 'height_cm', 'weight_kg', 'waist_circumference_cm', 'hip_circumference_cm', 'state']

Target classes:
provisional_age_span
45–49    14966
40–44    10851
50–54     5427
35–39     4667
30–34     1588
55–59     1281
25–29      597
60–65      385
Name: count, dtype: int64

Target leakage columns excluded: ['current_age', 'last_menstrual_period_year', 'approx_age_at_last_period', 'provisional_age_span']

In [21]:

# STEP 10: Stratified train/test split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training rows:", len(X_train))
print("Testing rows:", len(X_test))

print("\nTraining class distribution (%):")
display(
    (y_train.value_counts(normalize=True).sort_index() * 100)
    .round(2)
    .to_frame("percent")
)

print("\nTesting class distribution (%):")
display(
    (y_test.value_counts(normalize=True).sort_index() * 100)
    .round(2)
    .to_frame("percent")
)

print("\nMissing values in training features:", int(X_train.isna().sum().sum()))
print("Missing values in testing features:", int(X_test.isna().sum().sum()))

Training rows: 31809
Testing rows: 7953

Training class distribution (%):

                      percent
provisional_age_span
25–29                    1.50
30–34                    3.99
35–39                   11.74
40–44                   27.29
45–49                   37.64
50–54                   13.65
55–59                    3.22
60–65                    0.97

Testing class distribution (%):

                      percent
provisional_age_span
25–29                    1.50
30–34                    4.00
35–39                   11.74
40–44                   27.29
45–49                   37.63
50–54                   13.66
55–59                    3.22
60–65                    0.97

Missing values in training features: 29287
Missing values in testing features: 7140

In [15]:

%pip install -q xgboost catboost

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 11.2 MB/s eta 0:00:00

In [23]:

import pandas as pd
from sklearn.base import clone
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    f1_score
)
from sklearn.utils.class_weight import compute_sample_weight
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import (
    RandomForestClassifier,
    ExtraTreesClassifier,
    GradientBoostingClassifier
)
from xgboost import XGBClassifier
from catboost import CatBoostClassifier

# --------------------------------------------------
# 1. Encode target labels
# --------------------------------------------------
label_encoder = LabelEncoder()
y_train_encoded = label_encoder.fit_transform(y_train)
y_test_encoded = label_encoder.transform(y_test)

sample_weights = compute_sample_weight(
    class_weight="balanced",
    y=y_train_encoded
)

# --------------------------------------------------
# 2. Define baseline models and boosting variants
# --------------------------------------------------
experiments = [
    (
        "Logistic Regression",
        LogisticRegression(
            max_iter=2000,
            class_weight="balanced",
            random_state=42
        ),
        False
    ),
    (
        "Decision Tree",
        DecisionTreeClassifier(
            class_weight="balanced",
            random_state=42
        ),
        False
    ),
    (
        "Random Forest",
        RandomForestClassifier(
            n_estimators=300,
            class_weight="balanced",
            random_state=42,
            n_jobs=-1
        ),
        False
    ),
    (
        "Extra Trees",
        ExtraTreesClassifier(
            n_estimators=300,
            class_weight="balanced",
            random_state=42,
            n_jobs=-1
        ),
        False
    )
]

learning_rates = [0.03, 0.05, 0.1]

for lr in learning_rates:
    experiments.append((
        f"Gradient Boosting (lr={lr})",
        GradientBoostingClassifier(
            n_estimators=100,
            learning_rate=lr,
            max_depth=3,
            random_state=42
        ),
        True
    ))

for lr in learning_rates:
    experiments.append((
        f"XGBoost (lr={lr})",
        XGBClassifier(
            n_estimators=300,
            max_depth=5,
            learning_rate=lr,
            subsample=0.8,
            colsample_bytree=0.8,
            objective="multi:softprob",
            eval_metric="mlogloss",
            tree_method="hist",
            random_state=42,
            n_jobs=-1
        ),
        True
    ))

for lr in learning_rates:
    experiments.append((
        f"CatBoost (lr={lr})",
        CatBoostClassifier(
            iterations=300,
            learning_rate=lr,
            depth=6,
            loss_function="MultiClass",
            verbose=0,
            random_seed=42,
            allow_writing_files=False
        ),
        True
    ))

# --------------------------------------------------
# 3. Train and evaluate every configuration
# --------------------------------------------------
results = []
fitted_models = {}

for i, (name, model, use_weights) in enumerate(experiments, start=1):
    print(f"[{i}/{len(experiments)}] Training {name} ...")

    pipeline = Pipeline([
        ("preprocessor", clone(preprocessor)),
        ("classifier", model)
    ])

    fit_params = {}
    if use_weights:
        fit_params["classifier__sample_weight"] = sample_weights

    pipeline.fit(
        X_train,
        y_train_encoded,
        **fit_params
    )

    predictions = pipeline.predict(X_test).astype(int)

    results.append({
        "Model": name,
        "Accuracy": accuracy_score(
            y_test_encoded, predictions
        ),
        "Balanced Accuracy": balanced_accuracy_score(
            y_test_encoded, predictions
        ),
        "Macro F1": f1_score(
            y_test_encoded,
            predictions,
            average="macro",
            zero_division=0
        )
    })

    fitted_models[name] = pipeline

# --------------------------------------------------
# 4. Rank results
# --------------------------------------------------
results_df = (
    pd.DataFrame(results)
    .sort_values(
        ["Macro F1", "Balanced Accuracy"],
        ascending=False
    )
    .reset_index(drop=True)
)

display(results_df.round(4))

[1/13] Training Logistic Regression ...
[2/13] Training Decision Tree ...
[3/13] Training Random Forest ...
[4/13] Training Extra Trees ...
[5/13] Training Gradient Boosting (lr=0.03) ...
[6/13] Training Gradient Boosting (lr=0.05) ...
[7/13] Training Gradient Boosting (lr=0.1) ...
[8/13] Training XGBoost (lr=0.03) ...
[9/13] Training XGBoost (lr=0.05) ...
[10/13] Training XGBoost (lr=0.1) ...
[11/13] Training CatBoost (lr=0.03) ...
[12/13] Training CatBoost (lr=0.05) ...
[13/13] Training CatBoost (lr=0.1) ...

                          Model  Accuracy  Balanced Accuracy  Macro F1
0                   Extra Trees    0.4117             0.2063    0.2249
1                 Random Forest    0.4211             0.1944    0.2055
2                 Decision Tree    0.3165             0.2007    0.1964
3              XGBoost (lr=0.1)    0.2355             0.2161    0.1737
4             XGBoost (lr=0.05)    0.2031             0.2129    0.1570
5             CatBoost (lr=0.1)    0.1811             0.2252    0.1490
6             XGBoost (lr=0.03)    0.1836             0.2079    0.1467
7    Gradient Boosting (lr=0.1)    0.1666             0.1966    0.1354
8   Gradient Boosting (lr=0.05)    0.1594             0.1964    0.1309
9            CatBoost (lr=0.05)    0.1524             0.1992    0.1280
10          Logistic Regression    0.1493             0.1992    0.1252
11  Gradient Boosting (lr=0.03)    0.1461             0.1883    0.1221
12           CatBoost (lr=0.03)    0.1339             0.1957    0.1164

In [25]:
print("Target column:", y.name if hasattr(y, "name") else "Encoded target")
print("Input shape:", X.shape)
print("Target shape:", y.shape)

print("\nTarget class distribution:")
print(y.value_counts().sort_index())

print("\nPotential leakage columns:")
print([
    col for col in X.columns
    if any(term in col.lower() for term in [
        "last_menstrual_period",
        "approx_age_at_last_period",
        "provisional_age_span"
    ])
])

Target column: provisional_age_span
Input shape: (39762, 17)
Target shape: (39762,)

Target class distribution:
provisional_age_span
25–29      597
30–34     1588
35–39     4667
40–44    10851
45–49    14966
50–54     5427
55–59     1281
60–65      385
Name: count, dtype: int64

Potential leakage columns:
[]